#Here we will be creating a workflow that showcases how artifacts work with github actions.

name: Artifacts Demo
on: push

jobs:
    artifact-creation:
        runs-on: ubuntu-latest
        steps:
            - name: Create and edit file
              run: |
                touch "newfile"
                echo "Hello World" > newfile
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: my-artifact
                  path: /home/runner/work/GitHub_Actions_Demo/GitHub_Actions_Demo/newfile